use binary package

diff --git a/bin/pio-setup b/bin/pio-setup
--- a/bin/pio-setup
+++ b/bin/pio-setup
@@ -13,10 +13,11 @@ ES_HOME=$BASE_DIR/elasticsearch
 TARGET_DIR=$BASE_DIR/target
 TEMPLATE_DIR=$BASE_DIR/templates
 
+DEFAULT_PIO_VERSION=0.12.0-incubating
 DEFAULT_SCALA_VERSION=2.11.8
-DEFAULT_SPARK_VERSION=2.1.1
-DEFAULT_HADOOP_VERSION=2.6.5
-DEFAULT_ELASTICSEARCH_VERSION=5.5.3
+DEFAULT_SPARK_VERSION=2.2.0
+DEFAULT_HADOOP_VERSION=2.7.3
+DEFAULT_ELASTICSEARCH_VERSION=5.6.3
 DEFAULT_PIO_GIT_USER=jpioug
 DEFAULT_PIO_GIT_BRANCH=pio_setup
 
@@ -58,6 +59,9 @@ setup_all() {
   if [ x"$PIO_EVENTDATA_REFRESH" = x ] ; then
     PIO_EVENTDATA_REFRESH=false
   fi
+  if [ x"$PIO_VERSION" = x ] ; then
+    PIO_VERSION=$DEFAULT_PIO_VERSION
+  fi
 
   mkdir -p $TARGET_DIR
   setup_pio
@@ -77,27 +81,34 @@ setup_pio() {
   rm -rf $PIO_HOME
   cd $TARGET_DIR
 
-  if [ ! -d $PIO_GIT_REPO ] ; then
-    echo "Cloning PredictionIO..."
-    git clone https://github.com/$PIO_GIT_USER/$PIO_GIT_REPO.git
-    cd $PIO_GIT_REPO
-    if [ x"$PIO_GIT_BRANCH" != "xdevelop" ] ; then
-      git checkout -b $PIO_GIT_BRANCH origin/$PIO_GIT_BRANCH
+  if [ x"$PIO_VERSION" = "xgit" ] ; then
+    if [ ! -d $PIO_GIT_REPO ] ; then
+      echo "Cloning PredictionIO..."
+      git clone https://github.com/$PIO_GIT_USER/$PIO_GIT_REPO.git
+      cd $PIO_GIT_REPO
+      if [ x"$PIO_GIT_BRANCH" != "xdevelop" ] ; then
+        git checkout -b $PIO_GIT_BRANCH origin/$PIO_GIT_BRANCH
+      fi
+    else
+      cd $PIO_GIT_REPO
+    fi
+
+    echo "Building PredictionIO..."
+    bash ./make-distribution.sh \
+      -Dscala.version=$SCALA_VERSION \
+      -Dspark.version=$SPARK_VERSION \
+      -Dhadoop.version=$HADOOP_VERSION \
+      -Delasticsearch.version=$ELASTICSEARCH_VERSION \
+      $PIO_MAKE_OPTS
+    if [ $? != 0 ] ; then
+      echo "Build Failed!"
+      exit 1
     fi
   else
-    cd $PIO_GIT_REPO
-  fi
-
-  echo "Building PredictionIO..."
-  bash ./make-distribution.sh \
-    -Dscala.version=$SCALA_VERSION \
-    -Dspark.version=$SPARK_VERSION \
-    -Dhadoop.version=$HADOOP_VERSION \
-    -Delasticsearch.version=$ELASTICSEARCH_VERSION \
-    $PIO_MAKE_OPTS
-  if [ $? != 0 ] ; then
-    echo "Build Failed!"
-    exit 1
+    DOWNLOAD_SCALA_VERSION=`echo $SCALA_VERSION | sed -e "s/\(.*\)\.[0-9]*/\1/"`
+    DOWNLOAD_SPARK_VERSION=`echo $SPARK_VERSION | sed -e "s/\(.*\)\.[0-9]*/\1/"`
+    curl -s -L -o PredictionIO-${PIO_VERSION}.tar.gz \
+      https://github.com/jpioug/incubator-predictionio/releases/download/v${PIO_VERSION}-pio-setup/PredictionIO-${PIO_VERSION}_${DOWNLOAD_SCALA_VERSION}_${DOWNLOAD_SPARK_VERSION}.tar.gz
   fi
 
   echo "Deploying PredictionIO..."
@@ -151,7 +162,7 @@ setup_spark() {
 
   if [ ! -f $SPARK_FILE ] ; then
     echo "Downloading Spark..."
-    curl -o $SPARK_FILE http://d3kbcqa49mib13.cloudfront.net/$SPARK_FILE
+    curl -s -o $SPARK_FILE http://d3kbcqa49mib13.cloudfront.net/$SPARK_FILE
   fi
 
   echo "Deploying Spark..."
@@ -171,7 +182,7 @@ setup_es() {
 
   if [ ! -f $ES_FILE ] ; then
     echo "Downloading Elasticsearch..."
-    curl -o $ES_FILE https://artifacts.elastic.co/downloads/elasticsearch/$ES_FILE
+    curl -s -o $ES_FILE https://artifacts.elastic.co/downloads/elasticsearch/$ES_FILE
   fi
 
   echo "Deploying Elasticsearch..."
